mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [path('slot/', include('slot.urls')),
    path('admin/', admin.site.urls),
]

mysite/slot/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('dist', views.dist, name='dist'),
    path('login', views.login, name='login'),
    path('getdata', views.getdata, name='getdata'),
    path('register', views.register, name='register'),
    path('change', views.change, name='change'),
    path('putdata/<str:email>/<int:day>/<int:id>/', views.putdata, name='putdata')
]

mysite/slot/models.py
from django.db import models
from django.utils import timezone
import datetime

class Dist(models.Model):
    dist_name = models.CharField(max_length=50)
    dist_code = models.SmallIntegerField(primary_key=True)
    def __str__(self):
        return str(self.dist_code)

class Dist_new(models.Model):
    dist_name = models.CharField(max_length=50)
    dist_numb = models.SmallIntegerField()
    def __str__(self):
        return str(self.dist_name)

class Pin(models.Model):
    dist = models.ForeignKey(Dist, on_delete=models.CASCADE)
    pin_code = models.CharField(max_length=6, primary_key=True)
    def __str__(self):
        return self.pin_code

class User(models.Model):
    pin = models.ForeignKey(Pin, on_delete=models.CASCADE)
    email = models.EmailField(primary_key=True)
    d1 = models.BooleanField(default=True)
    d2 = models.BooleanField(default=True)
    notify = models.BooleanField()
    eight = models.BooleanField()
    five = models.BooleanField()
    cvsh = models.BooleanField()
    covax = models.BooleanField()
    sptk = models.BooleanField()
    free = models.BooleanField()
    paid = models.BooleanField()
    not_times = models.SmallIntegerField(default=0)
    time = models.DateTimeField(default = (timezone.now()-datetime.timedelta(hours = 6)))
    def __str__(self):
        return self.email


class Day(models.Model):
    usr = models.ForeignKey(User, on_delete=models.CASCADE)
    notify = models.BooleanField()
    day_numb = models.SmallIntegerField()
    def __str__(self):
        return str(self.day_numb)

class Time(models.Model):
    time = models.DateField(default = datetime.date.today())

    def change(self):
        days = Day.objects.all()
        for day in days:
            if day.day_numb > 1:
                day.day_numb -= 1
                day.save()
            else:
                day.day_numb = 5
                day.save()
                cents = Cent.objects.filter(day = day)
                for cent in cents:
                    cent.delete()


class Cent(models.Model):
    day = models.ForeignKey(Day, on_delete=models.CASCADE)
    cent_id = models.IntegerField()
    def __str__(self):
        return str(self.cent_id)

class Slice(models.Model):
    j = models.SmallIntegerField()
    k = models.SmallIntegerField()
    
    def get(self):
        dist = Dist.objects.order_by('dist_name')
        leng = len(dist)
        if self.k == leng:
            self.j = 0
            self.k = 0
        self.j = self.k
        self.k = self.k + 20
        if self.k>leng:
            self.k = leng
        return  (self.j, self.k)

mysite/slot/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse
import smtplib, ssl
from django.utils import timezone
import datetime
from .models import Cent, Day, Dist, Dist_new, Slice, Time
from .models import User
from .models import Pin


def index(request):
    dist = Dist.objects.order_by('dist_name')
    return render(request, 'slot/index.html', {'dist': dist})


def getdata(request):

    dtm = Time.objects.get(pk = 1)
    if dtm.time != datetime.date.today():
            dtm.change()
            dtm.time = datetime.date.today()
            dtm.save()

    dist = Dist.objects.order_by('dist_name')
    slice = Slice.objects.get(pk = 1)
    leng = len(dist)
    if slice.k == leng:
        slice.j = 0
        slice.k = 0
    slice.j = slice.k
    slice.k = slice.k + 20
    if slice.k>leng:
        slice.k = leng
    slice.save()

    dist = Dist.objects.order_by('dist_name')[slice.j:slice.k]

    return render(request, 'slot/getdata.html', {'dist': dist})


def dist(request):
    dist = Dist.objects.order_by('dist_name')
    try:
        dist_1 = Dist_new.objects.get(dist_name = request.POST['dist'])
    except Dist_new.DoesNotExist:
        dist_1 = Dist_new(dist_name = request.POST['dist'], dist_numb = 1)
        dist_1.save()
    else:
        dist_1.dist_numb += 1
        dist_1.save()  
        
    return render(request, 'slot/new_index.html', {'dist': dist, 'val' : 4})


def login(request):
    try:
        user = User.objects.get(email = request.POST['email'], pin = request.POST['pin'])
    except User.DoesNotExist:
        dist = Dist.objects.order_by('dist_name')
        return render(request, 'slot/new_index.html', {'dist': dist, 'val' : 1})
    else:
        pin_c = get_object_or_404(Pin, pin_code = request.POST['pin'])
        dist = Dist.objects.get(dist_code = pin_c.dist.dist_code)  
        return render(request, 'slot/detail.html', {'user': user, 'dist': dist, 'pin_c': pin_c})


def register(request):
    usr_eml = User.objects.all().values('email')
    if request.POST['email'] in [u['email'] for u in usr_eml]:
        dist = Dist.objects.order_by('dist_name')
        return render(request, 'slot/new_index.html', {'dist': dist, 'val' : 2})
    else:
        lst = ['notify', 'd1', 'd2', 'eight', 'five', 'free', 'paid', 'cvsh', 'covax', 'sptk']
        val = []
        cond = request.POST.getlist("condition")

        for i in range(len(lst)):
            if lst[i] in cond:
                val.append(True)
            else:
                val.append(False)

        dist = Dist.objects.get(dist_code = request.POST['d_code'])

        try:
            pinc = Pin.objects.get(pin_code = request.POST['pin'])
        except Pin.DoesNotExist:
            pinc = Pin(dist = dist, pin_code = request.POST['pin'])
            pinc.save()
            user = User(pin = pinc, email = request.POST['email'], notify = val[0], d1 = val[1], d2 = val[2], eight = val[3], five = val[4], free = val[5], paid = val[6], cvsh = val[7], covax = val[8], sptk = val[9], not_times = 0, time = timezone.now())
            user.save()
        else:
            user = User(pin = pinc, email = request.POST['email'], notify = val[0], d1 = val[1], d2 = val[2], eight = val[3], five = val[4], free = val[5], paid = val[6], cvsh = val[7], covax = val[8], sptk = val[9], not_times = 0, time = timezone.now())
            user.save()

        for i in range(1,6):
            day = Day(usr = user, notify = True, day_numb = i)
            day.save()

        dist = Dist.objects.order_by('dist_name')
        return render(request, 'slot/new_index.html', {'dist': dist, 'val' : 3})


def change(request):
    lst = ['notify', 'd1', 'd2', 'eight', 'five', 'free', 'paid', 'cvsh', 'covax', 'sptk']
    val = []
    cond = request.POST.getlist("condition")

    for i in range(len(lst)):
        if lst[i] in cond:
            val.append(True)
        else:
            val.append(False)

    user = User.objects.get(email = request.POST['email'])

    user.notify = val[0]
    user.d1 = val[1]
    user.d2 = val[2]
    user.eight = val[3]
    user.five = val[4]
    user.free = val[5]
    user.paid = val[6]
    user.cvsh = val[7]
    user.covax = val[8]
    user.sptk = val[9]
    user.save()

    return HttpResponseRedirect(reverse('index',))



def putdata(request, email, day, id):
    days = Day.objects.get(usr = email, day_numb = day)

    try:
        cent = Cent.objects.get(day = days, cent_id = id)
    except Cent.DoesNotExist:
        cent = Cent(day = days, cent_id = id)
        cent.save()
        user = User.objects.get(email = email)
        if user.not_times < 10:
            if user.time < (timezone.now() - datetime.timedelta(minutes = 10)):
                notify(email, 'early')
                user.not_times += 1
                user.time = timezone.now()
                user.save()
        else:
            notify(email, 'last')
            user.not_times = 0
            user.notify = False
            user.save()
    else:
        pass

    return HttpResponse("Task completed")




def notify(email, time):
    message1 = """\
Subject: Slot Alert

Hi..
There is/are new "VACANT" slots available (in the next 6 days) with the conditions you had requested. Please visit CoWIN website (https://www.cowin.gov.in/home) to check them and to book your slot.

This alert is purely based on CoWIN API data. If you think this is not useful then feel free to turn off the nitifications.

If you don't need mail alert anymore. Please log in at () to turn off the notification.

Yours,
Rahul"""

    message2 = """\
Subject: Last Slot Alert

Hi..
There is/are new "VACANT" slots available (in the next 6 days) with the conditions you had requested. Please visit CoWIN website (https://www.cowin.gov.in/home) to check them and to book your slot.

This is your 10th Slot Alert mail please login at () to turn on your notification again.

Yours,
Rahul"""


    if time == 'last':
        message = message2
    else:
        message = message1
    
    port = 465  # For SSL
    smtp_server = "smtp.gmail.com"

    s_email = "slot.update@gmail.com"  # Enter your address
    password = "second@wave"

    context = ssl.create_default_context()
    with smtplib.SMTP_SSL(smtp_server, port, context=context) as server:
        server.login(s_email, password)
        server.sendmail(s_email, email, message)
        

mysite/slot/templates/slot/detail.html
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<h2><font color="blue"><u>Covid Vaccination Slot Alert</u></font></h2>
<a href="{% url 'index' %}"><font color="orange"> Home Page</font></a>
<h3> Hey..<br>
  Here are your details: </h3>

  <form action="{% url 'change' %}" method="post">
    {% csrf_token %}

    <p>District: {{ dist.dist_name }}</p>

    <p>PinCode: {{ user.pin }}</p>

    <p>Email: {{ user.email }}</p>

    <input type="hidden" value="{{ user.email }}" name="email">
    
    <p><label for="notify">Keep next 10 notifications on:</label>
    <input type="checkbox" name="condition" value = "notify" {% if user.notify %}
    checked {% endif %}></p>

    <p>Notify me for:<br><br>
    <label for="d1">Dose 1:</label>
    <input type="checkbox" name="condition" value = "d1" {% if user.d1 %}
    checked {% endif %}>
    <label for="d2">Dose 2:</label>
    <input type="checkbox" name="condition"  value = "d2" {% if user.d2 %}
    checked {% endif %}></p>

    <p><label for="eight">Age 18+:</label>
    <input type="checkbox" name="condition"  value = "eight" {% if user.eight %}
    checked {% endif %}>
    <label for="five">Age 45+:</label>
    <input type="checkbox" name="condition"  value = "five" {% if user.five %}
    checked {% endif %}></p>

    <p><label for="free">Free:</label>
    <input type="checkbox" name="condition" value = "free" {% if user.free %}
    checked {% endif %}>
    <label for="paid">Paid:</label>
    <input type="checkbox" name="condition" value = "paid" {% if user.paid %}
    checked {% endif %}></p>

    <p><label for="cvsh">Covishield:</label>
    <input type="checkbox" name="condition" value = "cvsh" {% if user.cvsh %}
    checked {% endif %}></p>

    <p><label for="covax">Covaxin:</label>
    <input type="checkbox" name="condition" value = "covax" {% if user.covax %}
    checked {% endif %}></p>

    <p><label for="sptk">Sputnik V:</label>
    <input type="checkbox" name="condition" value = "sptk" {% if user.sptk %}
    checked {% endif %}></p>

    <input type="submit" value="Send">
  </form>

  Website developed and maintained by Rahul

mysite/slot/templates/slot/getdata.html
{ {% for dt in dist %}"{{dt.dist_code }}": 
        { {% for pins in dt.pin_set.all %}"{{pins.pin_code}}": 
                { {% for user in pins.user_set.all %} 
                    {% if user.notify %}
                        "{{user.email}}": {"slot":{ {% for day in user.day_set.all %}"{{ day.day_numb }}":
                                                            [{% for cent in day.cent_set.all %}{{ cent.cent_id }}{% if not forloop.last %},{% else %}
                                                                                                                {% endif %}
                                                            {% endfor %}]{% if not forloop.last %},{% else %}{% endif %}
                                                    {% endfor %}},                   
                                            "d1":"{{ user.d1 }}", 
                                            "d2":"{{ user.d2 }}", 
                                            "eight":"{{ user.eight }}", 
                                            "five":"{{ user.five }}", 
                                            "free":"{{ user.free }}", 
                                            "paid":"{{ user.paid }}", 
                                            "cvsh":"{{ user.cvsh }}", 
                                            "covax":"{{ user.covax }}", 
                                            "sptk":"{{ user.sptk }}"
                                        }{% if not forloop.last %},{% else %}
                                        {% endif %}
                    {% endif %}
                {% endfor %} 
                }{% if not forloop.last %},{% else %}
                    {% endif %}
        {% endfor %} 
        } {% if not forloop.last %},{% else %}
          {% endif %}
{% endfor %} }

mysite/slot/templates/slot/index.html
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<h2><font color="blue"><u>Covid Vaccination Slot Alert</u></font></h2>

<h3> Already registered..<br>
  Log in here: </h3>

<form action="{% url 'login' %}" method="post">
    {% csrf_token %}
    <p><label for="email">Email:</label>
    <input type="email" name="email"></p>
     <p><label for="pin">PinCode:</label>
    <input type="text" name="pin"> </p>
    <input type="submit" value="Send">
</form>

<br>


<h3> New User..<br>
    Register here: </h3>
  
<form action="{% url 'register' %}" method="post">
    {% csrf_token %}
    <p><label for="dist">District:</label>
        <select name="d_code">
            {% for dt in dist %}
                <option value={{dt.dist_code}}>{{dt.dist_name}}</option>
            {% endfor %}
        </select></p>

    <p><label for="pin">PinCode:</label>
    <input type="text" name="pin"></p>

    <p><label for="email">Email:</label>
    <input type="email" name="email"></p>
    
    <p><label for="notify">Keep next 10 notifications on:</label>
    <input type="checkbox" name="condition" value = "notify" checked></p>

    Notify me for:<br><br>
    <label for="d1">Dose 1:</label>
    <input type="checkbox" name="condition" value = "d1" checked>
    <label for="d2">Dose 2:</label>
    <input type="checkbox" name="condition"  value = "d2">

    <p><label for="eight">Age 18+:</label>
    <input type="checkbox" name="condition"  value = "eight" checked>
    <label for="five">Age 45+:</label>
    <input type="checkbox" name="condition"  value = "five"></p>

    <p><label for="free">Free:</label>
    <input type="checkbox" name="condition" value = "free" checked>
    <label for="paid">Paid:</label>
    <input type="checkbox" name="condition" value = "paid"></p>

    <p><label for="cvsh">Covishield:</label>
    <input type="checkbox" name="condition" value = "cvsh" checked></p>

    <p><label for="covax">Covaxin:</label>
    <input type="checkbox" name="condition" value = "covax" checked></p>

    <p><label for="sptk">Sputnik V:</label>
    <input type="checkbox" name="condition" value = "sptk" checked></p>

    <input type="submit" value="Send">
  </form>


<br>

<form action="{% url 'dist' %}" method="post">
    {% csrf_token %}
    <p><label for="dist">Couldn't find your district in the list add it here <br> we would update the list soon:</label>
    <input type="text" name="dist"> </p>
    <input type="submit" value="Send">
</form>

  Website developed and maintained by Rahul

mysite/slot/templates/slot/new_index.html
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<h2><font color="blue"><u>Covid Vaccination Slot Alert</u></font></h2>

{% if val == 3 %}<h3><font color="green">Successfully registered new user.</font></h3>
We will notify you for next 10 slots updates.<br>
After that please revisit the website to continue the service.{% endif %}

{% if val == 4 %}<h3><font color="green">Successfully noted your District.</font></h3>
We would add it soon in the list.{% endif %}

<h3> Already registered..<br>
  Log in here: </h3>

{% if val == 1 %}<font color="red">Incorrect data. Please refill.</font>{% endif %}
<form action="{% url 'login' %}" method="post">
    {% csrf_token %}
    <p><label for="email">Email:</label>
    <input type="email" name="email"></p>
     <p><label for="pin">PinCode:</label>
    <input type="text" name="pin"> </p>
    <input type="submit" value="Send">
</form>

<br>


<h3> New User..<br>
    Register here: </h3>
  
<form action="{% url 'register' %}" method="post">
    {% csrf_token %}
    <p><label for="dist">District:</label>
        <select name="d_code">
            {% for dt in dist %}
                <option value={{dt.dist_code}}>{{dt.dist_name}}</option>
            {% endfor %}
        </select></p>

    <p><label for="pin">PinCode:</label>
    <input type="text" name="pin"></p>

    {% if val == 2 %}<font color="red">Email already in use. Please use another email.</font>{% endif %}
    <p><label for="email">Email:</label>
    <input type="email" name="email"></p>
    
    <p><label for="notify">Keep next 10 notifications on:</label>
    <input type="checkbox" name="condition" value = "notify" checked></p>

    Notify me for:<br><br>
    <label for="d1">Dose 1:</label>
    <input type="checkbox" name="condition" value = "d1" checked>
    <label for="d2">Dose 2:</label>
    <input type="checkbox" name="condition"  value = "d2">

    <p><label for="eight">Age 18+:</label>
    <input type="checkbox" name="condition"  value = "eight" checked>
    <label for="five">Age 45+:</label>
    <input type="checkbox" name="condition"  value = "five"></p>

    <p><label for="free">Free:</label>
    <input type="checkbox" name="condition" value = "free" checked>
    <label for="paid">Paid:</label>
    <input type="checkbox" name="condition" value = "paid"></p>

    <p><label for="cvsh">Covishield:</label>
    <input type="checkbox" name="condition" value = "cvsh" checked></p>

    <p><label for="covax">Covaxin:</label>
    <input type="checkbox" name="condition" value = "covax" checked></p>

    <p><label for="sptk">Sputnik V:</label>
    <input type="checkbox" name="condition" value = "sptk" checked></p>

    <input type="submit" value="Send">
  </form>

<br>
<form action="{% url 'dist' %}" method="post">
    {% csrf_token %}
    <p><label for="dist">Couldn't find your district in the list <br> add it here we would update the list soon:</label>
    <input type="text" name="dist"> </p>
    <input type="submit" value="Send">
</form>

  Website developed and maintained by Rahul

mysite/slot/templates/slot/succ_reg.html
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<h3>Covid Vaccination Slot Alert</h3>
<a href="{% url 'index' %}"><font color="orange"> Home Page</font></a>
<h3><font color="green"> Hey..<br>
  Your data been saved successfully. </font></h3>
  We will notify you for next 10 slots updates.<br>
  After that please revisit the website to continue the service.